// ARRAYS ARE THE COLLECTION OF THE SIMILAR DATATYPES 
// int[]karan;    ...IT IS THE DECLARATION OF THE ARRAY IN THE STACK
// karan = new int[5]    :..... IT IS THE ACTUAL INITIALIZATION OF THE ARRAY IN THE HEAP MEMORY 
// int[] arr = new int[5]    ......THE LEFT PORTION TAKES PLACE AT THE COMPILE TIME AND RIGHT PORTION TAKES PLACE AT THE RUN TIME[(DMA)

// IMPORTANT:
//ARRAY OBJECTS ARE STORED IN THE HEAP AND IN JLS(JAVA LANGUAGAE SPECIFICATION) IT IS CLEARLY MENTIONED THAT HEAP OBJECTS ARE NOT CONTINUOUS  ; HENCE IN JAVA ARRAY OBJECTS MAY NOT BE CONTINUOS 
// NEW KEYWORD IS USED TO CREATE THE OBJECT.
//EACH ELEMENT OF THE ARRAY IS AN OBJECT AND STORED IN AN SPECIFIC MEMORY 